### ISSUE TITLE
term_for_sublime does not work on win8.1 x64 FileNotFoundError

### ISSUE THREAD

**Issue by adrianmak** [marijnh/tern_for_sublime#53]
ST3 build 3065 (32bit)

DPI scale: 1
startup, version: 3065 windows x32 channel: stable
executable: /D/Programs/SublimeText3/sublime_text.exe
working dir: /D/Programs/SublimeText3
packages path: /D/Programs/SublimeText3/Data/Packages
state path: /D/Programs/SublimeText3/Data/Local
hardware concurrency: 8
zip path: /D/Programs/SublimeText3/Packages
zip path: /D/Programs/SublimeText3/Data/Installed Packages
found 5 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 174 cache hits: 174
pre session restore time: 0.0609922
startup time: 0.0799922
first paint time: 0.0809922
launching: /D/Programs/SublimeText3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin Package Control.Package Control
reloading plugin tern_for_sublime.tern
loaded 837 snippets
plugins loaded
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\SublimeText3\sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "D:\Programs\SublimeText3\Data\Packages\tern_for_sublime\tern.py", line 531, in plugin_loaded
    subprocess.check_output(["npm", "install"], cwd=plugin_dir)
  File "./subprocess.py", line 576, in check_output
  File "./subprocess.py", line 824, in **init**
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
Package Control: Skipping automatic upgrade, last run at 2014-12-21 08:16:09, next run at 2014-12-21 09:16:09 or after

**Comment by EchoZulu** [comment]
Same problem 
win8.1 pro x64 / Sublime version: 3083 windows x64 
Nodejs is instaled correctly

=====================
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\tern_for_sublime\tern.py", line 581, in plugin_loaded
    subprocess.check_output(["npm", "install"], cwd=plugin_dir)
  File "./subprocess.py", line 576, in check_output
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by garthenweb** [comment]
See #84.
